name: melofify
description: Melofify music player

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  just_audio: ^0.9.36
  audio_session: ^0.1.16
  audio_service: ^0.18.18
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true